### ISSUE TITLE
使用minio作为s3存储，k8s部署picimpact，上传照片失败

### ISSUE THREAD

**Issue by yyzsec** [besscroft/PicImpact#197]
s3配置信息：
![Image](https://github.com/user-attachments/assets/46b9d0a9-431e-4cc2-b860-a5ec63dcf235)

console报错信息：
 [Error: getaddrinfo ENOTFOUND pic.http] {
   errno: -3008,
   code: 'ENOTFOUND',
   syscall: 'getaddrinfo',
   hostname: 'pic.http',
   '$metadata': [Object]
 }

代码中没找到相关的信息，貌似是请求网络的时候请求hostname变成了pic.http很奇怪。

**Comment by yyzsec** [comment]
附上k8s部署时候的配置，应该是没问题的：
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: picimpact-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: picimpact-config
  namespace: picimpact-system
data:
  DATABASE_URL: "postgresql://picimpactuser:[my-pass-****]@picimpact-postgresql:5432/picimpactdb"
  AUTH_SECRET: "[my-pass-****]"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: picimpact-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: picimpact-postgresql
  namespace: picimpact-system
spec:
  selector:
    matchLabels:
      app: picimpact-postgresql
  serviceName: "postgresql"
  replicas: 1
  template:
    metadata:
      labels:
        app: picimpact-postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: "picimpactdb"
        - name: POSTGRES_USER
          value: "picimpactuser"
        - name: POSTGRES_PASSWORD
          value: "[my-pass-****]"
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data/postgresql
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      storageClassName: longhorn
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: picimpact-postgresql
  namespace: picimpact-system
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None # Headless service for stateful set
  selector:
    app: picimpact-postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: picimpact
  namespace: picimpact-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picimpact
  template:
    metadata:
      labels:
        app: picimpact
    spec:
      containers:
        - name: picimpact
          image: besscroft/picimpact:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: picimpact-config
                  key: DATABASE_URL
            - name: AUTH_SECRET
              valueFrom:
                configMapKeyRef:
                  name: picimpact-config
                  key: AUTH_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: picimpact-service
  namespace: picimpact-system
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: picimpact
```
