### ISSUE TITLE
求助 docker compose部署失败

### ISSUE THREAD

**Issue by jupter000** [besscroft/PicImpact#25]
部署方式:docker compose
```
    postgresql:
        image: postgres:16.3-alpine
        container_name: postgresql
        hostname: postgresql
        restart: always
        networks:
            - all-in-one
        environment:
            - POSTGRES_USER=picimpact
            - POSTGRES_PASSWORD=aaaaaaa
            - POSTGRES_DB=picimpact
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - /home/picimpact_db:/var/lib/postgresql/data

    picimpact:
        restart: unless-stopped
        image: besscroft/picimpact:latest
        container_name: picimpact
        networks:
            - all-in-one
        ports:
            - 127.0.0.1:30109:3000
        environment:
            - DATABASE_URL="postgres://picimpact:aaaaaaa@postgresql:5432/picimpact"
            - AUTH_SECRET="bbbbbbbbbbbb"
        depends_on:
            - postgresql
```
### 错误日志
```
Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
  -->  prisma/schema.prisma:3
   | 
 2 |   provider = "postgresql"
 3 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
[Context: getConfig]

Prisma CLI Version : 5.14.0
npm notice 
npm notice New minor version of npm available! 10.5.0 -> 10.8.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.0>
npm notice Run `npm install -g npm@10.8.0` to update!
npm notice 
  ▲ Next.js 14.2.3
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Starting...
 ✓ Ready in 439ms
初始化数据失败，您可能需要准备干净的数据表，请联系管理员！ PrismaClientInitializationError: error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
  -->  schema.prisma:3
   | 
 2 |   provider = "postgresql"
 3 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at r (/app/node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:112:2493)
    at async wt.transaction (/app/node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:111:12070)
    at async Proxy._transactionWithCallback (/app/node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:127:9458)
    at async Module.t (/app/.next/server/instrumentation.js:1:356)
    at async NextNodeServer.prepareImpl (/app/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/next-server.js:475:17) {
  clientVersion: '5.13.0',
  errorCode: 'P1012'
```
搞不懂为什么连不上数据库

**Comment by besscroft** [comment]
@jupter000 您好，尝试删除环境变量的 `"` 符号，这似乎是 prisma 的 bug，由于我只用 Docker Desktop 和 k8s 进行了测试，所以没有发现这个问题（俺也不太会 docker compose）。删除双引号后，用你提供的 yml 测试正常，不过请注意声明 `Networks top-level elements`。

下面是我测试的完整的 yaml:

```yaml
name: pic
networks:
  pic:
services:
  postgresql:
    image: postgres:16.3-alpine
    container_name: postgresql
    hostname: postgresql
    restart: always
    networks:
      - pic
    environment:
      - POSTGRES_USER=picimpact
      - POSTGRES_PASSWORD=aaaaaaa
      - POSTGRES_DB=picimpact
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - /home/picimpact_db:/var/lib/postgresql/data
  picimpact:
    image: besscroft/picimpact:latest
    container_name: picimpact-test
    ports:
      - 3000:3000
    networks:
      - pic
    environment:
      - DATABASE_URL=postgres://picimpact:aaaaaaa@postgresql:5432/picimpact
      - AUTH_SECRET=bbbbbbbbbbbb
```

希望能帮到你！
