### ISSUE TITLE
如何设置Better Auth的trustedOrigins

### ISSUE THREAD

**Issue by Ranzeplay** [besscroft/PicImpact#322]
更新至2.6.0之后网站无法登录，Docker日志如下
```
INFO [Better Auth]: If it's a valid URL, please add https://gallery.ranzeplay.space to trustedOrigins in your auth config
Current list of trustedOrigins: http://gallery.ranzeplay.space
ERROR [Better Auth]: Invalid origin: https://gallery.ranzeplay.space
```
请问如何自定义`trustedOrigins`

**Comment by besscroft** [comment]
您是使用 vercel、nodejs 还是 docker 部署的？

**Comment by Ranzeplay** [comment]
Docker部署的，docker-compose如下（保密信息已隐藏）：
```yaml
version: "3.7"
services:
  db:
    image: postgres:17.5-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ***
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgsql-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - picimpact-net

  picimpact:
    image: besscroft/picimpact:latest
    container_name: picimpact
    restart: unless-stopped
    ports:
      - "40000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:***@db:5432/postgres"
      AUTH_SECRET: "***"
    depends_on:
      - db
    networks:
      - picimpact-net

volumes:
  pgsql-db-data:

networks:
  picimpact-net:
    driver: bridge
```
使用nginx反向代理，文件如下：
```yaml
server {
    listen 80;
    server_name ***;

    client_max_body_size 30M;

    location / {
        proxy_pass http://localhost:40000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```
使用了Cloudflare的SSL/TLS encryption，模式为Flexible
